# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: venture
# CHANGE-TO-YOURNAME-aws-node-http-api-project
service: aws-node-http-api-project

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
